//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Qyz.Model.Common
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class QYZEntity : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“QYZEntity”部分中的连接字符串初始化新 QYZEntity 对象。
        /// </summary>
        public QYZEntity() : base("name=QYZEntity", "QYZEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QYZEntity 对象。
        /// </summary>
        public QYZEntity(string connectionString) : base(connectionString, "QYZEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QYZEntity 对象。
        /// </summary>
        public QYZEntity(EntityConnection connection) : base(connection, "QYZEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Accounts> Sys_Accounts
        {
            get
            {
                if ((_Sys_Accounts == null))
                {
                    _Sys_Accounts = base.CreateObjectSet<Sys_Accounts>("Sys_Accounts");
                }
                return _Sys_Accounts;
            }
        }
        private ObjectSet<Sys_Accounts> _Sys_Accounts;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Menus> Sys_Menus
        {
            get
            {
                if ((_Sys_Menus == null))
                {
                    _Sys_Menus = base.CreateObjectSet<Sys_Menus>("Sys_Menus");
                }
                return _Sys_Menus;
            }
        }
        private ObjectSet<Sys_Menus> _Sys_Menus;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Modules> Sys_Modules
        {
            get
            {
                if ((_Sys_Modules == null))
                {
                    _Sys_Modules = base.CreateObjectSet<Sys_Modules>("Sys_Modules");
                }
                return _Sys_Modules;
            }
        }
        private ObjectSet<Sys_Modules> _Sys_Modules;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Role_Menu> Sys_Role_Menu
        {
            get
            {
                if ((_Sys_Role_Menu == null))
                {
                    _Sys_Role_Menu = base.CreateObjectSet<Sys_Role_Menu>("Sys_Role_Menu");
                }
                return _Sys_Role_Menu;
            }
        }
        private ObjectSet<Sys_Role_Menu> _Sys_Role_Menu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Role_Module> Sys_Role_Module
        {
            get
            {
                if ((_Sys_Role_Module == null))
                {
                    _Sys_Role_Module = base.CreateObjectSet<Sys_Role_Module>("Sys_Role_Module");
                }
                return _Sys_Role_Module;
            }
        }
        private ObjectSet<Sys_Role_Module> _Sys_Role_Module;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Role_System> Sys_Role_System
        {
            get
            {
                if ((_Sys_Role_System == null))
                {
                    _Sys_Role_System = base.CreateObjectSet<Sys_Role_System>("Sys_Role_System");
                }
                return _Sys_Role_System;
            }
        }
        private ObjectSet<Sys_Role_System> _Sys_Role_System;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Roles> Sys_Roles
        {
            get
            {
                if ((_Sys_Roles == null))
                {
                    _Sys_Roles = base.CreateObjectSet<Sys_Roles>("Sys_Roles");
                }
                return _Sys_Roles;
            }
        }
        private ObjectSet<Sys_Roles> _Sys_Roles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_Systems> Sys_Systems
        {
            get
            {
                if ((_Sys_Systems == null))
                {
                    _Sys_Systems = base.CreateObjectSet<Sys_Systems>("Sys_Systems");
                }
                return _Sys_Systems;
            }
        }
        private ObjectSet<Sys_Systems> _Sys_Systems;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Sys_Accounts EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Accounts(Sys_Accounts sys_Accounts)
        {
            base.AddObject("Sys_Accounts", sys_Accounts);
        }
    
        /// <summary>
        /// 用于向 Sys_Menus EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Menus(Sys_Menus sys_Menus)
        {
            base.AddObject("Sys_Menus", sys_Menus);
        }
    
        /// <summary>
        /// 用于向 Sys_Modules EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Modules(Sys_Modules sys_Modules)
        {
            base.AddObject("Sys_Modules", sys_Modules);
        }
    
        /// <summary>
        /// 用于向 Sys_Role_Menu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Role_Menu(Sys_Role_Menu sys_Role_Menu)
        {
            base.AddObject("Sys_Role_Menu", sys_Role_Menu);
        }
    
        /// <summary>
        /// 用于向 Sys_Role_Module EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Role_Module(Sys_Role_Module sys_Role_Module)
        {
            base.AddObject("Sys_Role_Module", sys_Role_Module);
        }
    
        /// <summary>
        /// 用于向 Sys_Role_System EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Role_System(Sys_Role_System sys_Role_System)
        {
            base.AddObject("Sys_Role_System", sys_Role_System);
        }
    
        /// <summary>
        /// 用于向 Sys_Roles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Roles(Sys_Roles sys_Roles)
        {
            base.AddObject("Sys_Roles", sys_Roles);
        }
    
        /// <summary>
        /// 用于向 Sys_Systems EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_Systems(Sys_Systems sys_Systems)
        {
            base.AddObject("Sys_Systems", sys_Systems);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Accounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Accounts : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Accounts 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="passWord">PassWord 属性的初始值。</param>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        public static Sys_Accounts CreateSys_Accounts(global::System.Int32 id, global::System.String userName, global::System.String passWord, global::System.Int32 roleID)
        {
            Sys_Accounts sys_Accounts = new Sys_Accounts();
            sys_Accounts.ID = id;
            sys_Accounts.UserName = userName;
            sys_Accounts.PassWord = passWord;
            sys_Accounts.RoleID = roleID;
            return sys_Accounts;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountName
        {
            get
            {
                return _AccountName;
            }
            set
            {
                OnAccountNameChanging(value);
                ReportPropertyChanging("AccountName");
                _AccountName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountName");
                OnAccountNameChanged();
            }
        }
        private global::System.String _AccountName;
        partial void OnAccountNameChanging(global::System.String value);
        partial void OnAccountNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Discribtion
        {
            get
            {
                return _Discribtion;
            }
            set
            {
                OnDiscribtionChanging(value);
                ReportPropertyChanging("Discribtion");
                _Discribtion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Discribtion");
                OnDiscribtionChanged();
            }
        }
        private global::System.String _Discribtion;
        partial void OnDiscribtionChanging(global::System.String value);
        partial void OnDiscribtionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Menus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Menus : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Menus 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="systemID">SystemID 属性的初始值。</param>
        public static Sys_Menus CreateSys_Menus(global::System.Int32 id, global::System.String name, global::System.Int32 systemID)
        {
            Sys_Menus sys_Menus = new Sys_Menus();
            sys_Menus.ID = id;
            sys_Menus.Name = name;
            sys_Menus.SystemID = systemID;
            return sys_Menus;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SystemID
        {
            get
            {
                return _SystemID;
            }
            set
            {
                OnSystemIDChanging(value);
                ReportPropertyChanging("SystemID");
                _SystemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SystemID");
                OnSystemIDChanged();
            }
        }
        private global::System.Int32 _SystemID;
        partial void OnSystemIDChanging(global::System.Int32 value);
        partial void OnSystemIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Modules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Modules : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Modules 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="menuID">MenuID 属性的初始值。</param>
        /// <param name="dllName">DllName 属性的初始值。</param>
        /// <param name="startUpClass">StartUpClass 属性的初始值。</param>
        public static Sys_Modules CreateSys_Modules(global::System.Int32 id, global::System.String name, global::System.Int32 menuID, global::System.String dllName, global::System.String startUpClass)
        {
            Sys_Modules sys_Modules = new Sys_Modules();
            sys_Modules.ID = id;
            sys_Modules.Name = name;
            sys_Modules.MenuID = menuID;
            sys_Modules.DllName = dllName;
            sys_Modules.StartUpClass = startUpClass;
            return sys_Modules;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                OnMenuIDChanging(value);
                ReportPropertyChanging("MenuID");
                _MenuID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuID");
                OnMenuIDChanged();
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DllName
        {
            get
            {
                return _DllName;
            }
            set
            {
                OnDllNameChanging(value);
                ReportPropertyChanging("DllName");
                _DllName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DllName");
                OnDllNameChanged();
            }
        }
        private global::System.String _DllName;
        partial void OnDllNameChanging(global::System.String value);
        partial void OnDllNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StartUpClass
        {
            get
            {
                return _StartUpClass;
            }
            set
            {
                OnStartUpClassChanging(value);
                ReportPropertyChanging("StartUpClass");
                _StartUpClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StartUpClass");
                OnStartUpClassChanged();
            }
        }
        private global::System.String _StartUpClass;
        partial void OnStartUpClassChanging(global::System.String value);
        partial void OnStartUpClassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parameter
        {
            get
            {
                return _Parameter;
            }
            set
            {
                OnParameterChanging(value);
                ReportPropertyChanging("Parameter");
                _Parameter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parameter");
                OnParameterChanged();
            }
        }
        private global::System.String _Parameter;
        partial void OnParameterChanging(global::System.String value);
        partial void OnParameterChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Role_Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Role_Menu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Role_Menu 对象。
        /// </summary>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="menuID">MenuID 属性的初始值。</param>
        public static Sys_Role_Menu CreateSys_Role_Menu(global::System.Int32 roleID, global::System.Int32 menuID)
        {
            Sys_Role_Menu sys_Role_Menu = new Sys_Role_Menu();
            sys_Role_Menu.RoleID = roleID;
            sys_Role_Menu.MenuID = menuID;
            return sys_Role_Menu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEnableChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Role_Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Role_Module : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Role_Module 对象。
        /// </summary>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="moduleID">ModuleID 属性的初始值。</param>
        public static Sys_Role_Module CreateSys_Role_Module(global::System.Int32 roleID, global::System.Int32 moduleID)
        {
            Sys_Role_Module sys_Role_Module = new Sys_Role_Module();
            sys_Role_Module.RoleID = roleID;
            sys_Role_Module.ModuleID = moduleID;
            return sys_Role_Module;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                if (_ModuleID != value)
                {
                    OnModuleIDChanging(value);
                    ReportPropertyChanging("ModuleID");
                    _ModuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModuleID");
                    OnModuleIDChanged();
                }
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEnableChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowAdd
        {
            get
            {
                return _AllowAdd;
            }
            set
            {
                OnAllowAddChanging(value);
                ReportPropertyChanging("AllowAdd");
                _AllowAdd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowAdd");
                OnAllowAddChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowAdd;
        partial void OnAllowAddChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowAddChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowEdit
        {
            get
            {
                return _AllowEdit;
            }
            set
            {
                OnAllowEditChanging(value);
                ReportPropertyChanging("AllowEdit");
                _AllowEdit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowEdit");
                OnAllowEditChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowEdit;
        partial void OnAllowEditChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowEditChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowDelete
        {
            get
            {
                return _AllowDelete;
            }
            set
            {
                OnAllowDeleteChanging(value);
                ReportPropertyChanging("AllowDelete");
                _AllowDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowDelete");
                OnAllowDeleteChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowDelete;
        partial void OnAllowDeleteChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowDeleteChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowSave
        {
            get
            {
                return _AllowSave;
            }
            set
            {
                OnAllowSaveChanging(value);
                ReportPropertyChanging("AllowSave");
                _AllowSave = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowSave");
                OnAllowSaveChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowSave;
        partial void OnAllowSaveChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowSaveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowQuery
        {
            get
            {
                return _AllowQuery;
            }
            set
            {
                OnAllowQueryChanging(value);
                ReportPropertyChanging("AllowQuery");
                _AllowQuery = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowQuery");
                OnAllowQueryChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowQuery;
        partial void OnAllowQueryChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowQueryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowReflesh
        {
            get
            {
                return _AllowReflesh;
            }
            set
            {
                OnAllowRefleshChanging(value);
                ReportPropertyChanging("AllowReflesh");
                _AllowReflesh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowReflesh");
                OnAllowRefleshChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowReflesh;
        partial void OnAllowRefleshChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowRefleshChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowView
        {
            get
            {
                return _AllowView;
            }
            set
            {
                OnAllowViewChanging(value);
                ReportPropertyChanging("AllowView");
                _AllowView = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowView");
                OnAllowViewChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowView;
        partial void OnAllowViewChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowViewChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowAudit
        {
            get
            {
                return _AllowAudit;
            }
            set
            {
                OnAllowAuditChanging(value);
                ReportPropertyChanging("AllowAudit");
                _AllowAudit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowAudit");
                OnAllowAuditChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowAudit;
        partial void OnAllowAuditChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowAuditChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowUnAudit
        {
            get
            {
                return _AllowUnAudit;
            }
            set
            {
                OnAllowUnAuditChanging(value);
                ReportPropertyChanging("AllowUnAudit");
                _AllowUnAudit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowUnAudit");
                OnAllowUnAuditChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowUnAudit;
        partial void OnAllowUnAuditChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowUnAuditChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowPrint
        {
            get
            {
                return _AllowPrint;
            }
            set
            {
                OnAllowPrintChanging(value);
                ReportPropertyChanging("AllowPrint");
                _AllowPrint = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowPrint");
                OnAllowPrintChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowPrint;
        partial void OnAllowPrintChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowPrintChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowExport
        {
            get
            {
                return _AllowExport;
            }
            set
            {
                OnAllowExportChanging(value);
                ReportPropertyChanging("AllowExport");
                _AllowExport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowExport");
                OnAllowExportChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowExport;
        partial void OnAllowExportChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowExportChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomA
        {
            get
            {
                return _AllowCustomA;
            }
            set
            {
                OnAllowCustomAChanging(value);
                ReportPropertyChanging("AllowCustomA");
                _AllowCustomA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomA");
                OnAllowCustomAChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomA;
        partial void OnAllowCustomAChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomAChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomB
        {
            get
            {
                return _AllowCustomB;
            }
            set
            {
                OnAllowCustomBChanging(value);
                ReportPropertyChanging("AllowCustomB");
                _AllowCustomB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomB");
                OnAllowCustomBChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomB;
        partial void OnAllowCustomBChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomC
        {
            get
            {
                return _AllowCustomC;
            }
            set
            {
                OnAllowCustomCChanging(value);
                ReportPropertyChanging("AllowCustomC");
                _AllowCustomC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomC");
                OnAllowCustomCChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomC;
        partial void OnAllowCustomCChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomD
        {
            get
            {
                return _AllowCustomD;
            }
            set
            {
                OnAllowCustomDChanging(value);
                ReportPropertyChanging("AllowCustomD");
                _AllowCustomD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomD");
                OnAllowCustomDChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomD;
        partial void OnAllowCustomDChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomE
        {
            get
            {
                return _AllowCustomE;
            }
            set
            {
                OnAllowCustomEChanging(value);
                ReportPropertyChanging("AllowCustomE");
                _AllowCustomE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomE");
                OnAllowCustomEChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomE;
        partial void OnAllowCustomEChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomF
        {
            get
            {
                return _AllowCustomF;
            }
            set
            {
                OnAllowCustomFChanging(value);
                ReportPropertyChanging("AllowCustomF");
                _AllowCustomF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomF");
                OnAllowCustomFChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomF;
        partial void OnAllowCustomFChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomFChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowCustomG
        {
            get
            {
                return _AllowCustomG;
            }
            set
            {
                OnAllowCustomGChanging(value);
                ReportPropertyChanging("AllowCustomG");
                _AllowCustomG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowCustomG");
                OnAllowCustomGChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowCustomG;
        partial void OnAllowCustomGChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowCustomGChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Role_System")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Role_System : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Role_System 对象。
        /// </summary>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="systemID">SystemID 属性的初始值。</param>
        public static Sys_Role_System CreateSys_Role_System(global::System.Int32 roleID, global::System.Int32 systemID)
        {
            Sys_Role_System sys_Role_System = new Sys_Role_System();
            sys_Role_System.RoleID = roleID;
            sys_Role_System.SystemID = systemID;
            return sys_Role_System;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SystemID
        {
            get
            {
                return _SystemID;
            }
            set
            {
                if (_SystemID != value)
                {
                    OnSystemIDChanging(value);
                    ReportPropertyChanging("SystemID");
                    _SystemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SystemID");
                    OnSystemIDChanged();
                }
            }
        }
        private global::System.Int32 _SystemID;
        partial void OnSystemIDChanging(global::System.Int32 value);
        partial void OnSystemIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEnableChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Roles : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Roles 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static Sys_Roles CreateSys_Roles(global::System.Int32 id, global::System.String name)
        {
            Sys_Roles sys_Roles = new Sys_Roles();
            sys_Roles.ID = id;
            sys_Roles.Name = name;
            return sys_Roles;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommonModel", Name="Sys_Systems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_Systems : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_Systems 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static Sys_Systems CreateSys_Systems(global::System.Int32 id, global::System.String name)
        {
            Sys_Systems sys_Systems = new Sys_Systems();
            sys_Systems.ID = id;
            sys_Systems.Name = name;
            return sys_Systems;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
