//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qyz.Model.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QYZEntity : DbContext
    {
        public QYZEntity()
            : base("name=QYZEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sys_Accounts> Sys_Accounts { get; set; }
        public DbSet<Sys_Menus> Sys_Menus { get; set; }
        public DbSet<Sys_Modules> Sys_Modules { get; set; }
        public DbSet<Sys_Role_Menu> Sys_Role_Menu { get; set; }
        public DbSet<Sys_Role_Module> Sys_Role_Module { get; set; }
        public DbSet<Sys_Role_System> Sys_Role_System { get; set; }
        public DbSet<Sys_Roles> Sys_Roles { get; set; }
        public DbSet<Sys_Systems> Sys_Systems { get; set; }
    }
}
