//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qyz.Model.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QYZ_CommonEntities : DbContext
    {
        public QYZ_CommonEntities()
            : base("name=QYZ_CommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Menu_Module> Menu_Module { get; set; }
        public DbSet<Module> Module { get; set; }
        public DbSet<Role_Menu> Role_Menu { get; set; }
        public DbSet<Role_Module> Role_Module { get; set; }
        public DbSet<Role_System> Role_System { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<System_Menu> System_Menu { get; set; }
        public DbSet<Systems> Systems { get; set; }
    }
}
